### ISSUE TITLE
[1.5.2] java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ProtocolSupport/ProtocolSupport#96] opened 2015-12-01 21:45 UTC
```
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[19:32:28] [Netty Server IO #1/WARN]: io.netty.handler.codec.DecoderException: NettyChannelInjector.decode() did not read anything but decoded a message.
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:268)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:32:28] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:281)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[19:32:28] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[19:32:28] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[19:32:28] [Server thread/INFO]: nathampa0909 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: NettyChannelInjector.decode() did not read anything but decoded a message.
[19:32:28] [Server thread/INFO]: nathampa0909 left the game.
```
I know that this error is not very useful, however, this was happening when me and my friend was testing AAC on my test server with ProtocolSupport (He was using 1.5.2), maybe this can help you to find the bug more easier. :smile: 

If I find a way to reproduce this bug, I will post here.

**Comment by Shevchik** [comment] 2015-12-01 21:48
Protocol support channel injector is not present at player channel for whatever reason, can't really check issues in non-opensource plugins.

**Comment by MrPowerGamerBR** [comment] 2015-12-01 21:51
@Shevchik :+1:

**Comment by swan201** [comment] 2015-12-02 08:33
That issue is AAC Problem. AAC try to kick 1.5.2 user, than 1.8 over client get kick mesaage. but below clinet get just java error.

**Comment by MrPowerGamerBR** [comment] 2015-12-02 10:27
@swan201 thanks for the explanation!

Strange that this error only happens with AAC, because other plugins can kick 1.5.2 clients without any error (one example is my AntiKillAura plugin)

**Comment by swan201** [comment] 2015-12-02 11:27
@MrPowerGamerBR That is why Shevchik say hard to fix this issue. because AAC is none open Source Code Plugins. So we cant debug that error :)

**Comment by MrPowerGamerBR** [comment] 2015-12-02 14:18
After sometime testing (without AAC, or whatever plugin) my friend using 1.7.10 was getting kicked without doing anything (He was just standing, and randomly the server would disconnect with the same error)

**Comment by Shevchik** [comment] 2015-12-02 14:25
That means that we need additional debug info to find it out. I will add advenaced logger later.

**Comment by swan201** [comment] 2015-12-02 16:39
@Shevchik But AAC require Protocollib :) hard to reproducing without protocollib.

**Comment by swan201** [comment] 2015-12-14 12:49
@MrPowerGamerBR If you want to use aac with Protocolsupport, Then try to turn off BadPacket Option.

**Comment by Shevchik** [comment] 2015-12-24 15:21
This should be recheked now because of the rewrite of how protocolsupport encoder/decoder works now.

**Comment by nathampa0909** [comment] 2016-02-26 00:43
@Shevchik I think you can close this issue, the error disappeared, should be when you change the encoder/decoder.

**Closed** 2016-02-26 03:28 UTC
