### ISSUE TITLE
1.9 and 1.10 Potion issue.

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#766] opened 2018-01-29 23:21 UTC
https://imgur.com/a/fREef

Pretty much the exact same issue with 1.8.9 and lower. I have noticed the potion texture in 1.10 is fine, just no splash effect.

**Comment by Shevchik** [comment] 2018-01-29 23:22
Known wontfix issues:

    [1.8 and earlier] Thrown potion texture is invalid

**Comment by MasterDash5** [comment] 2018-01-29 23:33
I'm aware you won't fix it for 1.8.9. If you read it I SAID 1.9 and 1.10

**Comment by MasterDash5** [comment] 2018-01-29 23:53
I dont wanna leave you hanging so I'll show you most of the code i used for ProtocolSupportPotions.

PacketListeners: https://pastebin.com/Gv7KU5mG
ConversionUtils: https://pastebin.com/BBaGikFQ
ProtocolUtils: https://pastebin.com/HQd7T46W

**Comment by Shevchik** [comment] 2018-01-30 00:00
That ain't gonna work in all cases (when potion entity ain't real for example). Also async access to entity storage is potentially unsafe. Should probably be added to ProtocolSupportLegacySupport plugin instead, because it can be at least reloaded while server is running.

**Comment by MasterDash5** [comment] 2018-01-30 13:52
Mostly just showed you it as a reference so you don't have to start from nothing. took me 2 weeks to figure out all the ids for the potion texture and splashes. Anyways, anything else I can help you with I'd be happy to

**Comment by Shevchik** [comment] 2018-02-09 09:00
Fixed it for 1.9. But can't reproduce the same for 1.10.2. Which 1.10 versions are affected?

**Comment by MasterDash5** [comment] 2018-02-10 21:07
The 1.10 potion texture works fine, just the splash effect is missing.

1.10: https://imgur.com/a/zXJSC
1.11 and higher: https://imgur.com/a/iy1nt

1.9 was missing both the potion texture and splash effect

**Comment by Shevchik** [comment] 2018-02-11 07:12
Will be hard to fix. Potions now trigger effect by sending an rgb mix of potion effect colors.
In previous version it was just the potion id. Converting it at network level will be really hard if not impossible. Most likely it requires operating on server directly and injecting custom potion implementation. Or at least a sync platform specific packet listening. So i guess it is a task for ProtocolSupportLegacySupport.

**Comment by MasterDash5** [comment] 2018-02-11 16:40
Isn't 1.8.9 and lower the same thing just with different id numbers?

**Comment by MasterDash5** [comment] 2018-02-17 17:25
I made a new ProtocolSupportPotions that translates the particle effect (or world event). I hope it'll help. I haven't uploaded this code to spigot incase you fix the bug.

PacketListeners: [https://pastebin.com/LkA3U0aR](url)
ConversionUtils: [https://pastebin.com/qGbVdy21](url)
ProtocolUtils: [https://pastebin.com/e5xvjv3S](url)

**Comment by Shevchik** [comment] 2018-02-24 12:11
Will fix that is PSLS, and will remap potion break effect to generic one in PS itself (better at least see something instead of nothing at all)

**Comment by 7kasper** [comment] 2018-10-03 09:37
This issue will be continued in: https://github.com/ProtocolSupport/ProtocolSupportLegacySupport/issues/4.

**Closed** 2018-10-03 09:37 UTC
Labels: bug
