### ISSUE TITLE
Error kicking players

### ISSUE THREAD

**Issue by NEZNAMY** [ProtocolSupport/ProtocolSupport#459] opened 2017-04-13 09:02 UTC
https://pastebin.com/jZuRMtf1

After joining it instantly kicks me. Using build 41, works fine with 38.

**Comment by sionzeecz** [comment] 2017-04-13 16:35
Same here

Using Paper-Spigot: 1.11.2-R0.1-SNAPSHOT (1081)
ProtoclSupport: [#41](https://build.true-games.org/job/ProtocolSupport/41/)

`Error occured at 2017-04-13-18-31
Additional info: bband-dyn152.178-40-251.t-com.sk/178.40.251.152:58537, MINECRAFT_1_11_1
Exception class: io.netty.handler.codec.EncoderException
Exception message: java.lang.NullPointerException
Exception log:
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:52)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.write(ChannelInjector.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at protocolsupport.protocol.pipeline.common.LogicHandler.write(LogicHandler.java:46)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
	at net.minecraft.server.v1_11_R1.NetworkManager$4.run(NetworkManager.java:204)
	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException`

**Comment by Shevchik** [comment] 2017-04-13 21:03
Will fix it soon.

**Comment by oloflarsson** [comment] 2017-04-14 15:36
Also after downgrading to build #40 no one can see the hat layer of their skins.

**Comment by Shevchik** [comment] 2017-04-14 16:39
Downgrade to build 38 for now

**Comment by 7kasper** [comment] 2017-04-14 16:39
@oloflarsson use build 38 (#455) The EntityMeta remappers are being rewritten.

**Comment by 7kasper** [comment] 2017-04-14 16:39
Derp :P

**Comment by Shevchik** [comment] 2017-04-15 08:00
Should be fixed now

**Closed** 2017-04-16 21:42 UTC
Labels: bug
