### ISSUE TITLE
No textures of the colored beds in inventory

### ISSUE THREAD

**Issue by goblin9700** [ProtocolSupport/ProtocolSupport#527] opened 2017-06-23 14:07 UTC
The textures of the colored beds are not displayed from the client 1.11 in the inventory on the server 1.12.
Version server git-Spigot-4df3c0c-03f1e37 (MC: 1.12)
ProtocolSupport version 4.26.dev

**Comment by gdude2002** [comment] 2017-06-23 14:10
You can only dye beds in 1.12. That functionality does not exist in 1.11, and so it won't be visible.

ProtocolSupport is not magic and cannot patch the client. The most that could be done is to provide the bed colour in mouse-over text.

**Comment by goblin9700** [comment] 2017-06-23 14:24
Other blocks, for example, coloured concrete have a texture.

**Comment by gdude2002** [comment] 2017-06-23 14:25
Are you saying that the coloured beds have the purple/black "missing texture" icon?

**Comment by goblin9700** [comment] 2017-06-23 14:27
Yes, "missing texture" icon on the blocks.

**Comment by gdude2002** [comment] 2017-06-23 14:28
Ah, okay, must be caused by the metadata changes...

@Shevchik is currently going to be busy until around the 7th of July, but he might have time to stop in and issue a couple bugfixes before that.

**Comment by Shevchik** [comment] 2017-06-30 14:09
ItemStack remapper needs to be rewritten to support item data.

**Comment by Shevchik** [comment] 2017-07-07 15:52
Should be fixed now

**Closed by Shevchik** 2017-07-07 15:52 UTC
Labels: bug
