### ISSUE TITLE
Eating bug

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#474] opened 2017-05-08 15:59 UTC
On 1.8 (i don't know about other versions), when you eat something and don't change your tool and release your mouse after you finish eating, the server will think you are still eating and eat it, even if you don't see it and can fight, run etc.

**Comment by gdude2002** [comment] 2017-05-08 16:00
What version of ProtocolSupport and Spigot are you using?

**Comment by DanielAlves123** [comment] 2017-05-08 20:01
The newest.

**Comment by gdude2002** [comment] 2017-05-08 20:22
We need exact version numbers to be sure of that.

**Comment by DanielAlves123** [comment] 2017-05-08 21:16
I can't check it, but it's the newest and you can check it very easy.

**Comment by gdude2002** [comment] 2017-05-08 21:17
You created the ticket, why can't you check?

It's difficult for us to help you without that information. "Newest" is not helpful as it could mean several different versions of both, depending on where you got them from.

**Comment by DanielAlves123** [comment] 2017-05-09 09:51
I just can't check ProtocolSupport version, it shows 'Invalid command'. But it's 2 versions behind the newest. Downloaded via Jenkins.

Spigot (downloaded via BuildTools):
This server is running CraftBukkit version git-Spigot-a3f6ea5-6194f6c (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
You are 8 version(s) behind

**Comment by Shevchik** [comment] 2017-05-10 05:06
Most likely a problem with entity action remapper

**Comment by DanielAlves123** [comment] 2017-05-15 20:59
@Shevchik when can we see the fix? :)

**Comment by Shevchik** [comment] 2017-05-15 21:09
It will probably be fixed in 1.12 release

**Comment by Shevchik** [comment] 2017-05-21 13:21
Well, apparently i don't understand what you mean exactly, record a video with a problem please.

**Comment by DanielAlves123** [comment] 2017-05-25 11:29
Here's the link. If you have any other questions just ask here. http://www51.zippyshare.com/v/E2iopAnb/file.html

**Comment by DanielAlves123** [comment] 2017-07-05 13:36
Can someone help? @Shevchik

**Comment by 7kasper** [comment] 2017-07-06 09:46
@DanielAlves123 I'm unable to reproduce the issue in 1.8 with the latest version of ProtocolSupport. Do you have any other plugins that do _anything_ with food? Perhaps there's a small compatibility issue.

**Comment by DanielAlves123** [comment] 2017-07-08 14:01
I reproduced it instantly, you have to read what i wrote.

**Comment by Shevchik** [comment] 2017-07-12 09:14
Well, if you don't release the mouse it will continue eating next item, that's what 1.8 client does. Don't see a bug there.

**Closed** 2017-07-12 09:16 UTC
Labels: bug, need more info

**Comment by DanielAlves123** [comment] 2017-07-20 12:25
@Shevchik as you can see I released the mouse, I just ate 1 apple, then I held right click for just a half second or something like that. I didn't stop eating and it continued to eat the apple, even if i didn't hold the mouse.

**Comment by Shevchik** [comment] 2017-07-20 12:55
Unable to reproduce, eating stops just fine. Remove all client and server modifications, and try again.
