### ISSUE TITLE
1.8.9 clients see ghost items on killing player (slot-dependent)

### ISSUE THREAD

**Issue by PixelPerfect** [ProtocolSupport/ProtocolSupport#1232] opened 2020-04-08 15:15 UTC
Timings report for server info (plugins/version): https://timings.aikar.co/?id=40a62a592a0b4de69f9ee4132a249d85#plugins

# Reproduction steps:
1.15.2 player has an item in any of the following slots:
- Main-hand selected slot
- Helmet slot
- Chest slot
- Leggings slot
- Boots slot

1.15.2 client is killed by a player who is running 1.8.9 (other versions not checked by me)
1.8.9 player sees these items drop twice.
1.8.9 player can only pick up one of these pairs of items.
Remaining ghost items remain on floor for 1.8.9 client.

**Comment by Shevchik** [comment] 2020-04-08 15:39
A duplicate of #1200

**Closed by Shevchik** 2020-04-08 15:39 UTC
