### ISSUE TITLE
[1.14.2] Hologram problem

### ISSUE THREAD

**Issue by OverBrave** [ProtocolSupport/ProtocolSupport#1107] opened 2019-06-06 21:53 UTC
I can't see the holograms when installed to procotol support.
Procotolsupport version: 1.14.2 #39 dev build
HolographicDisplays version: 1.14.2 #83 dev build
Paper version: 1.14.2 Paper #68

**Comment by krusic22** [comment] 2019-06-06 21:54
Duplicate of: #1092

**Comment by Shevchik** [comment] 2019-06-06 21:54
We don't accept issues for 1.14.2 branch yet. Also it's a duplicate.

**Closed by Shevchik** 2019-06-06 21:54 UTC
