### ISSUE TITLE
Bug, 1.8.x Client click Villager, on 1.13.2 Server

### ISSUE THREAD

**Issue by bilemedimkq** [ProtocolSupport/ProtocolSupport#1022] opened 2019-02-11 11:30 UTC
bug: Click villager and Kick the game

http://prntscr.com/mjihix
http://prntscr.com/mjiich

server: 1.13.2 Paper
client: 1.8.8
ps version: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.02.06 at 10:39:54 MSK, buildhost: build.true-games.org, buildnumber: 350)

**Comment by Shevchik** [comment] 2019-02-12 07:48
I'm unable to reproduce this.
Remove all other plugins and try again. If this still happen paste a schematic containing that villager there.

**Comment by bilemedimkq** [comment] 2019-02-12 09:39
http://prntscr.com/mjynfo

**Comment by Shevchik** [comment] 2019-02-12 09:45
Yes, make sure you copied the entities.

**Comment by bilemedimkq** [comment] 2019-02-12 10:19
I could not save entities as schematic. how can I do that ?

**Comment by Shevchik** [comment] 2019-02-12 10:23
Just paste the whole world then. The error itself however is caused by ps thinking that opened inventory is player one, which may have different causes.

**Comment by bilemedimkq** [comment] 2019-02-12 10:31
Paper jar
ps jar
world folder

http://www.ghostmc.net/naber.zip

**Comment by bilemedimkq** [comment] 2019-02-12 10:32
coordinate: -96 6 79

**Comment by Shevchik** [comment] 2019-02-12 12:10
Apparently server sends items update for villager before actually sending inventory open.
I had patched this in my local copy of the server, which explains why i couldn't reproduce this at first.
Will have to ignore the item updates for mismatching window id i guess, however still worth reporting that to spigot i guess.

**Comment by Shevchik** [comment] 2019-02-13 06:04
Fixed in spigot in https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/51c118b1d7f6ed9847fa853081e1eed67ddeb293

**Closed by Shevchik** 2019-02-13 06:04 UTC
Labels: bug
