### ISSUE TITLE
1.8 Ground glitch

### ISSUE THREAD

**Issue by gaberilde** [ProtocolSupport/ProtocolSupport#426] opened 2017-03-19 20:12 UTC
sometimes the ground glitches on 1.8 when you join while using 1.11.2 version.

if you die on the server it will be fixed

**Comment by Shevchik** [comment] 2017-03-19 22:07
Try to reproduce that glitch. It exists for already a long time, and nobody have any idea what causes it because it's hard to reproduce.

**Comment by robotman3000** [comment] 2017-03-19 22:36
When the player spawns does he fall through the ground? Is that what is meant by the ground glitches?

**Comment by robotman3000** [comment] 2017-03-19 22:38
If it is then a possible explanation is that the player spawns and starts falling before the world, and the block colision layers with it, is loaded

**Comment by gaberilde** [comment] 2017-03-20 07:47
it kinda looks like im falling through the ground il show u a video its easist when the server has just loaded BTW you can join before some plugins are loaded like permissions and such

**Comment by gaberilde** [comment] 2017-03-20 07:55
i got a video of it it actually seems to happen most if you dont log out at spawn like if you logout in your last location in the same world i think

heres a video:   [https://youtu.be/XoTur_M6Nbk](url)

**Comment by Shevchik** [comment] 2017-03-20 10:41
Post the ip of the server, i will try to join and debug what's happening clientside.

**Comment by gaberilde** [comment] 2017-03-20 16:10
Ok but the server is currently in beta and only certain people may join at this point

IP: Gabrielo.ga OR Alt.GabrieloT.ga << try if the first dosent work

so please tell me your username and i can add you

if your name is the same on github as it is ingame then i already added you and will be seeing you ingame soon.

also creative (/gamemode 1) and fly should be work you will be displayed as member rank

**Comment by Shevchik** [comment] 2017-03-20 16:37
_Shevchik_

**Comment by Shevchik** [comment] 2017-03-20 16:47
It's not the same, markdown fucks up things. My nickname is Shevchik with unrescore before and after the nickname.

**Comment by gaberilde** [comment] 2017-03-20 16:59
i think i done it right but not 100% sure what underscore is if you cant join just let me know but try

i can get your name when you join if it is wrong and il correct it

**Comment by jojoe77777** [comment] 2017-03-21 01:58
`_Shevchik_` ?

**Comment by gaberilde** [comment] 2017-03-21 07:42
it dosent matter anymore but thanks anyway i did get it myself

**Comment by Shevchik** [comment] 2017-03-21 08:37
So the problem reproduces even if you disable all the packets besides start game, respawn, position and chunk data. Which means no other packets are the issue. Also replacing received block data with stone doesn't help too, which means the chunk data itself is not the problem too.
Also more interesting things:
1) The problem only reproduces reliably with server view distance over 6.
2) If client render distance is set to more than 26 chunks problem dissapears.
3) Chunk sending has something to do with it, because the results change based on which chunks were received first, and how fast it was.

**Comment by FurmigaHumana** [comment] 2017-04-09 08:27
This is actually a minecraft bug [[MC-90602]](https://bugs.mojang.com/browse/MC-90602) that has been around since 1.9, nothing to do with protocolsupport.

On < 1.8 chunks used to be sent in bulk, one packet with 5-something chunks on every tick. Now since 1.9 they are sent individualy as they load, which means that the client can recieve every chunk in his field of view in one tick if they are all loaded overloading the renderer not giving it enough time to process everything, causing those visual glitches.

I fixed this by changing how spigot send chunks to reduce how many are sent at once and it fixed the issue, but i dont think this is up to protocolsupport.

**Comment by gaberilde** [comment] 2017-04-09 08:30
hi some useful info here what u change it too?

**Comment by FurmigaHumana** [comment] 2017-04-09 09:00
Sadly I cant share the full code because it is extensily modified which a lot of things that are only useful/work for me. 

You will need to get the spigor source code and change the PlayerChunk.class and EntityPlayer.class to make it look more like it was on 1.8, the original code send chunks as they load like this:

```
//original code
    public boolean b() {
            ...
              ....
            PacketPlayOutMapChunk packetplayoutmapchunk....
            Iterator iterator = this.c.iterator();

            while (iterator.hasNext()) {
                EntityPlayer entityplayer = (EntityPlayer) iterator.next();

                entityplayer.playerConnection.sendPacket(packetplayoutmapchunk);
                this.playerChunkMap.getWorld().getTracker().a(entityplayer, this.chunk);
            }
```

what I changed was just to instead of sending right away, it has to first be enqueue for each player, each will have its sending queue

```
// mod of code above on PlayerChunk.class
           for (EntityPlayer entityplayer : players.keySet()) {
                entityplayer.sendQueue(location);
            }

// EntityPlayer.class
    private final List<ChunkCoordIntPair> sendqueue = Memory.newArrayList();
    private int sendthrottle = 0;
    public void sendQueue(ChunkCoordIntPair pair) {
        sendqueue.add(pair);
    }
```

And consume the queue on every tick with only a few packets at once, this will basically simulate how packets used to be sent on <1.8

```
// changes on EntityPlayer.class
public void A_() {
// A_ is the method called on every tick
        int throttle = 10;
        int bulk = 5;

        if (sendthrottle < throttle) {
            
            sendthrottle++;
            
        } else {

            sendthrottle = 0;

            for (int j1 = 0; j1 < bulk && !sendqueue.isEmpty(); j1++) {
                this.x().manager.sendChunk(this, sendqueue.remove(0));
            }
        }
```

One or two other places also send chunks, they also need to be replaced to put on queue.

I dont know if @Shevchik can implement something like this on ProtocolSupport, specialy since i dont think every server is affected by this.

**Comment by 7kasper** [comment] 2017-04-09 09:27
@FurmigaHumana And that works? If what you said fixed the issue then 1.8 (like MCPE) can't handle too many packets (or at least chunkdata) at once. 

For now, people with this issue just need lower the view-distance as that seems to resolve the problem.

You could implement a queue but I fear doing this in the plugin itself will create a bottleneck. If the player flies around too much, more and more chunk packets will be added to the queue and other packets will be delayed as well.

A fix to that might be to add priority to packets and remove the chunkpackets from the queue if the chunkunload packet is called.

**Comment by Shevchik** [comment] 2017-04-09 09:30
Don't forget that you will also have to queue all other chunk related packets, such as tile and block updates. Not an easy task.

**Comment by FurmigaHumana** [comment] 2017-04-09 19:06
@7kasper yes it fixed the issue 100%, no more chunk glitches have been reported to me ever since. There is a few alternatives that might help, like teleporting to another world on join (to flush the client chunk cache, maybe can we fake it with packets?) but this is not 100% and still glitches sometimes.

Lowering the view distance should do the trick as it will also reduce how many chunks are sent at once, so I guess this could be an easier solution for servers with this issue, even if is not a full fix but it will sure make it rare and when it happens F3 + A will fix it.

--

@Shevchik Yes indeed, by modifing how chunks are sent we also need to take care of entities and tiles, the entity tracker also need to be adapted to not send entities for players if the chunk is not yet sent or else they will be invisible.. easy to do on spigot side, but not so much on protocolsupport.

Block updates on the other hand can be sent first, the client will see them even with the chunk unloaded and when the chunk packet arrive it will take care of merging it.

**Comment by BestMark** [comment] 2017-06-19 10:36
Just checked resolution from @FurmigaHumana with Spigot code editing and it helps resolve the problem. But I changed "_int throttle_" from _10_ to _2_ because chunks were loading very slowly.

**Comment by Shevchik** [comment] 2018-03-07 01:09
I'm back at trying to fix that issue. But now i need a map where i can stable reproduce this, to check if the network delay is working.

**Comment by gaberilde** [comment] 2018-03-07 09:05
My server? IP is changed its now gabrielo.freeddns.org

**Comment by gaberilde** [comment] 2018-03-07 10:51
I will when I get access to my server again in a few hours

**Comment by Shevchik** [comment] 2018-03-08 13:39
.

**Comment by Shevchik** [comment] 2018-03-10 23:05
Should be fixed now. At least i tried locally and it worked. Try it on your server too. If it doesn't work right at the start - try tweaking the interval by setting java property protocolsupport.chunksend18interval to interval at which chunks should be sent (in ms, default is 5ms).

**Comment by gaberilde** [comment] 2018-03-11 07:19
Ok i will install it and try

**Comment by gaberilde** [comment] 2018-03-11 11:29
When i install the latest version and start the server it clicks stop by it self with seemingly no errors?????

**Comment by Shevchik** [comment] 2018-03-11 11:39
Check the whole log, it will print what is wrong at plugin load.

**Comment by gaberilde** [comment] 2018-03-11 11:44
ok i found the error:
Severe: [ProtocolSupport] Unsupported server implementation type or version

**Comment by Shevchik** [comment] 2018-03-11 12:02
Which means you aren't using latest spigot or glowstone build

**Comment by gaberilde** [comment] 2018-03-11 12:30
im on 1.11.2 thoruh if i update it might break my plugins tho

**Comment by Shevchik** [comment] 2018-03-11 12:59
Well, we are not supporting old server versions, so you will have to update or backport the changes yourself.

**Comment by gaberilde** [comment] 2018-03-11 14:58
Updated and i got over 5+ severe plugin issues so i cant use your plugin anymore.
Switching to viaversion + viabackwards & viarewind

**Closed** 2018-03-11 15:15 UTC
Labels: bug, help wanted
