### ISSUE TITLE
NoSuchMethodError: 'void net.minecraft.network.PacketDecompressor.<init>

### ISSUE THREAD

**Issue by DarkyCat** [ProtocolSupport/ProtocolSupport#1353] opened 2021-08-05 22:31 UTC
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information: I can not log into the server from the client 1.17.1
The problem appeared today before that everything was fine. The developers said that this is not a problem with the Airplane. (Console error: https://mcpaste.io/75eaba68a24b63d5)
* ProtocolSupport version (/ps buildinfo) [buildtime=2021.07.31 at 16:57:33 MSK, buildhost=https://build.true-games.org, buildnumber=647, buildgit=https://github.com/ProtocolSupport/ProtocolSupport/commit/a98977e7b6d17ecbfb35ee85fe184d0701cd95fc]
* Server version: Airplane (Paper fork) 1.17.1

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

**Comment by Shevchik** [comment] 2021-08-05 22:36
Try on one of the supported platforms first

**Comment by pkt77** [comment] 2021-08-05 22:52
This is also caused by the Tuinity fork, this commit: https://github.com/Tuinity/Tuinity/commit/5620c5720691a99ff0761093c1dab66833ecad15

I reverted it so I can run PS.

**Comment by astei** [comment] 2021-08-06 20:52
It's my fault. But the way ProtocolSupport implements its own compression pipeline completely negates any benefit from my patch. Unfortunately, I have no choice but to implement a constructor that satisfies ProtocolSupport's expectations.

**Comment by Shevchik** [comment] 2021-08-06 21:01
ProtocolSupport pipeline uses heap buffers only (due to internal packet data buffers using heap memory in order to avoid dealing with reference counting), so you won't be able to use native compression anyway.

**Comment by astei** [comment] 2021-08-12 19:28
I don't have the time to fix this issue.

**Comment by astei** [comment] 2021-08-31 21:15
Paper has merged all of Tuinity, including my patch. I still don't have time to fix the issue.

**Comment by Shevchik** [comment] 2021-09-01 12:13
Paper does have an old consturctor just for this case.

**Closed by Shevchik** 2021-09-01 12:13 UTC
