### ISSUE TITLE
1.14.4 does not allow users to join

### ISSUE THREAD

**Issue by spotlightishere** [ProtocolSupport/ProtocolSupport#1134] opened 2019-07-22 05:16 UTC
Hi! We're running 1.14.4 with the CI build for 220abb82fa197c234de9713f8271a795ee7b45d7 (https://build.true-games.org/job/ProtocolSupport/394/). Our server is running [Waterfall](https://github.com/PaperMC/Waterfall) and is connecting to a Paper 1.14.4 server as well.

Unfortunately, users cannot join due to what seems to be a casting error.
<details><summary>Full stacktrace</summary><p>

```txt
[00:04:00 INFO]: [ProtocolSupport] /localip:53963 connected with protocol version MINECRAFT_1_14_4
[00:04:00 WARN]: java.lang.ClassCastException: com.destroystokyo.paper.profile.ProfileProperty incompatible with protocolsupport.api.utils.ProfileProperty
[00:04:00 WARN]: at protocolsupport.zplatform.impl.spigot.network.SpigotNetworkManagerWrapper$$Lambda$4034.00000000F80CC620.apply(Unknown Source)
[00:04:00 WARN]: at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[00:04:00 WARN]: at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[00:04:00 WARN]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
[00:04:00 WARN]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[00:04:00 WARN]: at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[00:04:00 WARN]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241)
[00:04:00 WARN]: at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[00:04:00 WARN]: at protocolsupport.zplatform.impl.spigot.network.SpigotNetworkManagerWrapper.setSpoofedProfile(SpigotNetworkManagerWrapper.java:121)
[00:04:00 WARN]: at protocolsupport.protocol.packet.handler.AbstractHandshakeListener.handleSetProtocol(AbstractHandshakeListener.java:72)
[00:04:00 WARN]: at protocolsupport.zplatform.impl.spigot.network.handler.SpigotHandshakeListener.a(SpigotHandshakeListener.java:26)
[00:04:00 WARN]: at net.minecraft.server.v1_14_R1.PacketHandshakingInSetProtocol.a(PacketHandshakingInSetProtocol.java:31)
[00:04:00 WARN]: at net.minecraft.server.v1_14_R1.PacketHandshakingInSetProtocol.a(PacketHandshakingInSetProtocol.java:5)
[00:04:00 WARN]: at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:153)
[00:04:00 WARN]: at net.minecraft.server.v1_14_R1.NetworkManager.channelRead0(NetworkManager.java:142)
[00:04:00 WARN]: at net.minecraft.server.v1_14_R1.NetworkManager.channelRead0(NetworkManager.java:29)
[00:04:00 WARN]: at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[00:04:00 WARN]: at protocolsupport.utils.netty.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:56)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[00:04:00 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:245)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[00:04:00 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[00:04:00 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[00:04:00 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:263)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decodeRaw(InitialPacketDecoder.java:186)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:142)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:123)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:36)
[00:04:00 WARN]: at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[00:04:00 WARN]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[00:04:00 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[00:04:00 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[00:04:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[00:04:00 WARN]: at java.lang.Thread.run(Thread.java:813)
[00:04:00 WARN]: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.07.20 at 08:41:30 MSK, buildhost: build.true-games.org, buildnumber: 394, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:220abb82fa197c234de9713f8271a795ee7b45d7)): Network exception occured(connection: protocolsupport.protocol.ConnectionImpl(profile: protocolsupport.protocol.utils.authlib.GameProfile(onlineMode: false, originalname: null, originaluuid: null, name: null, uuid: null, properties: {}), player: null, address: /external:53963, rawaddress: /localip:53963, version: MINECRAFT_1_14_4, metadata: {}))
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.common.LogicHandler.exceptionCaught(LogicHandler.java:60)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[00:04:00 WARN]: at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[00:04:00 WARN]: at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[00:04:00 WARN]: at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[00:04:00 WARN]: at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[00:04:00 WARN]: at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[00:04:00 WARN]: at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[00:04:00 WARN]: at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[00:04:00 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.exceptionCaught(ChannelInjector.java:385)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[00:04:00 WARN]: at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[00:04:00 WARN]: at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[00:04:00 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:263)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decodeRaw(InitialPacketDecoder.java:186)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:142)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:123)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:36)
[00:04:00 WARN]: at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[00:04:00 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[00:04:00 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[00:04:00 WARN]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[00:04:00 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[00:04:00 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[00:04:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[00:04:00 WARN]: at java.lang.Thread.run(Thread.java:813)
[00:04:00 WARN]: Caused by: io.netty.handler.codec.DecoderException: Unable to transform or read packet data [0, 15, 115, 112, 111, 116, 108, 105, 103, 104, 116, 95, 105, 115, 95, 111, 107]
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.version.util.decoder.AbstractPacketDecoder.throwFailedTransformException(AbstractPacketDecoder.java:53)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.decode(AbstractModernPacketDecoder.java:33)
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.decode(AbstractModernPacketDecoder.java:11)
[00:04:00 WARN]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[00:04:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[00:04:00 WARN]: ... 34 more
[00:04:00 WARN]: Caused by: io.netty.handler.codec.DecoderException: Did not read all data from packet, bytes left: 15
[00:04:00 WARN]: at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.decode(AbstractModernPacketDecoder.java:30)
[00:04:00 WARN]: ... 37 more
```
</p>
</details>

An abbreviated version:

```
[00:04:00 WARN]: java.lang.ClassCastException: com.destroystokyo.paper.profile.ProfileProperty incompatible with protocolsupport.api.utils.ProfileProperty
[00:04:00 WARN]: Caused by: io.netty.handler.codec.DecoderException: Unable to transform or read packet data [0, 15, 115, 112, 111, 116, 108, 105, 103, 104, 116, 95, 105, 115, 95, 111, 107]
[00:04:00 WARN]: Caused by: io.netty.handler.codec.DecoderException: Did not read all data from packet, bytes left: 15
```
These bytes (hex `000f73706f746c696768745f69735f6f`) are often the remote username being sent through but slightly cut off, though if spammed more often goes to other parts internally.
At this point, the upstream Waterfall server does not continue to log in and fails connection.

**Comment by spotlightishere** [comment] 2019-07-22 05:36
We've since determined that this is an issue with our build of Waterfall. Appreciate all the time all contributors put into this amazing project!

**Comment by Artuto** [comment] 2019-07-22 07:10
Actually... just checked and does happen with Vanilla Waterfall build 298

**Comment by Artuto** [comment] 2019-07-22 22:35
Full log: https://gist.github.com/Artuto/70bbb08be3056c1b02e908ad50e73414

**Comment by Shevchik** [comment] 2019-07-23 02:12
This error doesn't make sense. Sounds more like java invokedynamic failure.

**Comment by Artuto** [comment] 2019-07-23 02:15
We're using OpenJDK 8 with OpenJ9 (different JVM).

Could it be because of that? 1.13.2 PS worked just fine with it though

**Comment by Artuto** [comment] 2019-07-24 03:44
Tested with normal Oracle Java 8 and still occurs, may be down to a plugin?

**Comment by Artuto** [comment] 2019-07-24 04:08
Confirmed to be caused by BungeeGuard.

**Comment by lucko** [comment] 2019-07-24 20:11
Issue is not "caused" by BungeeGuard.

The plugin is simple - uses only one Paper event.

https://github.com/lucko/BungeeGuard/blob/master/bungeeguard-backend/src/main/java/me/lucko/bungeeguard/backend/BungeeGuardBackendPlugin.java

I suspect ProtocolSupport's handling of the PlayerHandshakeEvent is broken.

**Comment by Shevchik** [comment] 2019-07-25 00:25
Inedeed, the code handling the PlayerHandshakeEvent was broken (was using wrong property class (and since java generics are erased, we got the wrong list in the end)). 
Should be fixed now.

**Comment by Artuto** [comment] 2019-07-29 15:48
Confirmed the fix works. You can close now

**Closed** 2019-07-29 15:49 UTC
Labels: unable to reproduce
