### ISSUE TITLE
1.7.x and below clients cannot walk on carpets and stairs

### ISSUE THREAD

**Issue by Lachney** [ProtocolSupport/ProtocolSupport#1139] opened 2019-07-25 03:57 UTC
Running on Bungee, 1.7.x clients cannot walk on carpets and ladders

protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.07.25 at 03:24:25 MSK, buildhost: build.true-games.org, buildnumber: 400, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:939a9e0da24c0f2626f985524e9654bc5c7a23e9)

This server is running Paper version git-Paper-145 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by krusic22** [comment] 2019-07-25 03:58
Duplicate of #1121.

**Comment by Shevchik** [comment] 2019-07-27 15:57
Fixed

**Closed** 2019-07-29 10:21 UTC
Labels: bug
