### ISSUE TITLE
maps created with mapartcrafts map.dat option crash when seen

### ISSUE THREAD

**Issue by arceuss** [ProtocolSupport/ProtocolSupport#1294] opened 2020-10-23 17:29 UTC
using paper 1.16.3
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.09.11 at 02:03:01 MSK, buildhost: https://build.true-games.org, buildnumber: 564, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/7914f24cf9bed285350030daf1a65ad48f210606)
[crash-2020-10-23_11.28.30-client.txt](https://github.com/ProtocolSupport/ProtocolSupport/files/5430905/crash-2020-10-23_11.28.30-client.txt)

**Comment by arceuss** [comment] 2020-10-23 17:30
other maps dont crash tho

**Comment by arceuss** [comment] 2020-10-24 00:34
hmm other plugins that make images into maps seem to crash aswell
on 1.8 its just blank

**Comment by Shevchik** [comment] 2020-10-24 09:02
That is caused by new map colors. Will fix that soon.

**Comment by arceuss** [comment] 2020-10-24 15:25
alright

**Comment by Shevchik** [comment] 2020-10-30 19:01
Should probably be fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/05b4610f0f88679e9ccf4fa5ae0326c7e0660bfa.

**Comment by arceuss** [comment] 2020-11-01 03:47
![image](https://user-images.githubusercontent.com/28229451/97794670-acb3c500-1bc2-11eb-89d8-62d64da6c768.png)
it works

**Closed** 2020-11-01 16:46 UTC
Labels: bug
