### ISSUE TITLE
Boat glitch 1.8

### ISSUE THREAD

**Issue by Matthew18Dev** [ProtocolSupport/ProtocolSupport#758] opened 2017-12-18 22:43 UTC
Hi,
players on my server reported a glitch with boats (I discovered that this is happening in 1.8 and earlier), whenever they use a boat, client-side it's like they are moving okay, but other players see them standing still into the same block they started from, also, if they leave the boat they immediately get teleported back to their starting position.

[Screenshot](https://imgur.com/a/tTV5w)

**Comment by gdude2002** [comment] 2017-12-18 22:44
Known wontfix issues:
[1.8 and earlier] Can't control vehicle

Duplicate of #757

**Closed by gdude2002** 2017-12-18 22:44 UTC
