### ISSUE TITLE
Unable to sign books in 1.8

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#340] opened 2016-12-17 22:52 UTC
With an 1.8 client on a 1.11 server it is impossible to sign books - they look signed, but if you rejoin or drop it, it will be an unsigned book again.

**Comment by Shevchik** [comment] 2017-01-11 01:46
Strange the plugin channel name is still the same, so it should definitely work. Maybe something is wrong with message contents.

**Comment by Shevchik** [comment] 2017-01-12 06:48
Should be fixed now

**Comment by Brokkonaut** [comment] 2017-01-14 15:33
It is now possible to sign books in 1.8, but the text content is slightly broken - if you create a book in 1.8 and sign it, newlines appear as "\n" in the text and some characters display as "\u003d" and similar and there are double quotes around the whole text.

**Comment by Shevchik** [comment] 2017-01-23 09:26
That's a separate issue caused by the fact that mojang always changes how client sends data.
Create a separate issue for that.

Fixing this will require a client->server itemstack transformer, but thats a low priority.

**Closed by Shevchik** 2017-01-23 09:26 UTC
Labels: bug
