### ISSUE TITLE
Can't Shift-Double-Click Items From Chest

### ISSUE THREAD

**Issue by ghost** [ProtocolSupport/ProtocolSupport#719] opened 2017-10-17 18:03 UTC
Hello,

I made an issue concerning this exact problem some time ago only to find out the issue had actually been "resolved" or rather, was not occurring at the time. I've received some complaints that the issue was persisting again, this time I decided to reproduce the issue on an isolated "dummy instance" with the latest Spigot and ProtocolSupport build.

With ProtocolSupport:
https://i.imgur.com/SzgmhVp.gif

Without ProtocolSupport:
https://i.imgur.com/HzIzHHW.gif

**Comment by MasterDash5** [comment] 2017-10-18 03:48
oh... thats what that was... i thought my anticheat just hated me LOL

**Comment by krusic22** [comment] 2017-10-19 07:59
ViaVersion fixed this just a little while ago. Might be worth looking at their solution.

**Comment by 7kasper** [comment] 2017-10-19 09:14
What version's are affected? I cannot reproduce using mc 1.12.2 and latest version of PS and Spigot...

**Comment by MasterDash5** [comment] 2017-10-19 16:25
i know 1.8.9 clients and lower are affected

**Comment by LucidEcstasy** [comment] 2017-10-19 18:36
From what I understand this affected all versions 1.8-1.12. ViaVersion wouldn't solve this problem since ViaVersion doesn't work that way, I'm already using 1.12.2 Spigot so obviously, there's nothing to inject there.

**Comment by Shevchik** [comment] 2017-10-22 09:30
I guess it's about difference in sent inventory packets. Will look into it when i have time.

**Comment by 7kasper** [comment] 2017-10-22 09:42
I did notice that wiki.vg says that mode is encoded as VarInt enum, while ProtocolSupport (still) reads and sends it as an unsigned byte.

**Comment by Shevchik** [comment] 2017-10-22 09:43
Varint enum and byte has no difference for values < 127

**Comment by didjee2** [comment] 2017-11-01 18:08
We also have this problem, it effects any client below 1.12, above it all works.
We're now just telling them to play 1.12 :P.

**Comment by UberMC** [comment] 2018-01-26 19:14
I'm shift Double L.Click 
https://gyazo.com/07dfca75323423c79d4e2b1e38bfb91b

A lot of players complain about this and it appears to be an important part of minecraft.

**Comment by 7kasper** [comment] 2018-05-09 15:20
Said this some time ago in discord.
Regarding the inventory double click, as @krusic22 pointed out it was fixed in viaversion (https://github.com/MylesIsCool/ViaVersion/pull/754) I suppose we need to delay a packet or two?

In that PR we can see what packets we need to reorder.

**Comment by Speentie8081** [comment] 2018-05-09 17:14
yes please fix this. Its annoying always having to use the latest version
of mitecraft for shift double click from an inventory.

**Comment by LinsaFTW** [comment] 2018-06-28 18:51
Please fix :(

**Comment by Shevchik** [comment] 2019-03-23 23:03
Fixed

**Closed** 2019-03-25 14:33 UTC
Labels: bug, help wanted

**Comment by TouchBrown** [comment] 2020-07-12 21:21
> Fixed

I'm running a 1.12.2 paper server is there a jar with this patch that will work for me

**Comment by Kynoani** [comment] 2020-07-12 23:32
> 
> 
> > Fixed
> 
> I'm running a 1.12.2 paper server is there a jar with this patch that will work for me

Make the same changes as in [this commit](https://github.com/ProtocolSupport/ProtocolSupport/commit/70c1cdf54aa4ea410faa8e38b1406e27d75f4407) in a clone of the repository from back when 1.12.2 was supported.
If you are having trouble getting the code from the 1.12 version of the plugin, use the following commands.
`git clone https://github.com/ProtocolSupport/ProtocolSupport`
`cd ProtocolSupport`
`git checkout a2e767e2211da69177da82cfabb8a2fbd2f79b0b`
Then make the same changes as in that commit and then type
`./gradlew assemble`
I have retired from supporting this project to any meaningful extent and no longer have discord, best of luck to you.

**Comment by TouchBrown** [comment] 2020-07-13 22:20
> > > Fixed
> > 
> > 
> > I'm running a 1.12.2 paper server is there a jar with this patch that will work for me
> 
> Make the same changes as in [this commit](https://github.com/ProtocolSupport/ProtocolSupport/commit/70c1cdf54aa4ea410faa8e38b1406e27d75f4407) in a clone of the repository from back when 1.12.2 was supported.
> If you are having trouble getting the code from the 1.12 version of the plugin, use the following commands.
> `git clone https://github.com/ProtocolSupport/ProtocolSupport`
> `cd ProtocolSupport`
> `git checkout a2e767e2211da69177da82cfabb8a2fbd2f79b0b`
> Then make the same changes as in that commit and then type
> `./gradlew assemble`
> I have retired from supporting this project to any meaningful extent and no longer have discord, best of luck to you.

Thank you lots for the help.  It looks like this is 1.13 do you know if it will work or if there is another commit that I should checkout

**Comment by Kynoani** [comment] 2020-07-13 22:49
> 
> 
> > > > Fixed
> > > 
> > > 
> > > I'm running a 1.12.2 paper server is there a jar with this patch that will work for me
> > 
> > 
> > Make the same changes as in [this commit](https://github.com/ProtocolSupport/ProtocolSupport/commit/70c1cdf54aa4ea410faa8e38b1406e27d75f4407) in a clone of the repository from back when 1.12.2 was supported.
> > If you are having trouble getting the code from the 1.12 version of the plugin, use the following commands.
> > `git clone https://github.com/ProtocolSupport/ProtocolSupport`
> > `cd ProtocolSupport`
> > `git checkout a2e767e2211da69177da82cfabb8a2fbd2f79b0b`
> > Then make the same changes as in that commit and then type
> > `./gradlew assemble`
> > I have retired from supporting this project to any meaningful extent and no longer have discord, best of luck to you.
> 
> Thank you lots for the help. It looks like this is 1.13 do you know if it will work or if there is another commit that I should checkout

It should work fine, there is a version of the class that was used in the 1.12 version of the plugin, it should have a very similar name. Just make the same changes in that class as was done in the 1.13 class and you should be golden.

**Comment by Kynoani** [comment] 2020-07-13 22:55
My bad the correct tree for 1.12 would be accessible with the following command.
`git checkout 6f3b8b878e967d64b03f1a81685ffe2bba54f4a8`
Disregard the one in my original comment, I didn't go back far enough when I hastily wrote that comment.
The 1.12 version of the class is src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_4_5_6_7_8_9r1_9r2_10_11_12r1_12r2/InventoryClick.java
After making the changes type `./gradlew assemble` and the jar will be created in `target/`

**Comment by TouchBrown** [comment] 2020-07-14 15:38
Thank you so much for everything I got it working :)
