### ISSUE TITLE
Issues with horses

### ISSUE THREAD

**Issue by SofieHL** [ProtocolSupport/ProtocolSupport#404] opened 2017-03-04 22:18 UTC
1.10 or 1.11 server with 1.8.9 client: players cant see saddles on horses, open horse inventory, or ride horses.

**Comment by Speentie8081** [comment] 2017-03-07 02:08
Yeah this has been coming up a lot lately, though, it doesn't bother me personally.
Also that #404 number though on this issue thread, so funny.

**Comment by CakeLancelot** [comment] 2017-03-09 07:40
The README states:

> Known wontfix issues:
>     [1.8 and earlier] Can't control vehicle

Now if this applies to horses I'm not sure - the bugs involving inventory and saddles are probably valid though.

**Comment by Shevchik** [comment] 2017-03-20 12:50
Duplicate of already existing bugs, horses meta is unimplemented.

**Closed by Shevchik** 2017-03-20 12:50 UTC
