### ISSUE TITLE
Custom maps bugging

### ISSUE THREAD

**Issue by utkabobr** [ProtocolSupport/ProtocolSupport#522] opened 2017-06-18 11:37 UTC
Good afternoon!
I'm working on a plugin with custom maps, it works fine for 1.12, but can't render on 1.11.2 with ProtocolSupport
My friend's screenshot(1.11.2): http://i.imgur.com/btVUu7Y.png
Mine screenshot(1.12): http://i.imgur.com/NZ56BXB.png
Hope I can be useful somewhere

**Comment by Brokkonaut** [comment] 2017-06-19 14:23
Mojang has changed the palette for maps in 1.12. It might have something to do with that
http://minecraft.gamepedia.com/Map_item_format#1.12_Color_Table

**Comment by utkabobr** [comment] 2017-06-19 18:14
Okay, thanks, I'll try to do something with that in my plugin part

**Comment by Shevchik** [comment] 2017-06-30 14:11
New color codes needs to be remapped.

**Comment by MrSpock78** [comment] 2017-07-01 16:03
I have some problems with custom maps too. I have 3 different plugins on my server that are using custom maps. Only one of them is still showing every custom map made by this plugin to all users.
Seems that some colors or blocks are not compatible with older versions.

**Comment by utkabobr** [comment] 2017-07-10 10:23
`public class MapListener extends PacketAdapter {
	public MapListener(Plugin plugin, ListenerPriority listenerPriority, PacketType type) {
		super(plugin, listenerPriority, type);
	}
	
	@Override
    public void onPacketSending(PacketEvent event) {
		if (Bukkit.getPluginManager().getPlugin("ProtocolSupport")==null) return;
		PacketContainer packet = event.getPacket();
		byte[] data = packet.getByteArrays().read(0);
		if (ProtocolSupportAPI.getProtocolVersion(event.getPlayer()).isBefore(ProtocolVersion.MINECRAFT_1_12)) {
			for (int x = 0; x < 128; ++x) {
	            for (int y = 0; y < 128; ++y) {
	            	if (data.length >= (y * 128 + x+1)) {
		                byte pixel = (byte) (data[y * 128 + x]/4);
		                Boolean cng = false;
	                		if (pixel<0) {
	    	                	int a, b;
	    	                	a = -12;
	    	                	b = 29;
	    	                	for (; a >= -27; a--, b--) {
	    	                		if (pixel==a) pixel = (byte) b;
	    	                	}
	    	                	if (pixel<0) pixel = 29;
	    	                	cng = true;
	    	                }
		                if (cng) data[y * 128 + x] = (byte) (pixel*4);
	            	}
	            }
	        }
		}
		packet.getByteArrays().write(0, data);
	}
}`
Remapped with ProtocolLib

**Comment by MrSpock78** [comment] 2017-07-10 16:54
Thank you, this looks like a solution :) But I´m not a dev :( How or where can I use this code on my server?

**Comment by utkabobr** [comment] 2017-07-11 08:17
1. Create an empty plugin
2. Add ProtocolLib as dependency(To build path)
3. Paste that to a class (MapListener or rename it in the code)
4. Add ProtocolLibrary.getProtocolManager().addPacketListener(new MapListener(this, ListenerPriority.MONITOR, PacketType.Play.Server.MAP)); to your main class
5. Build the plugin and install it

**Comment by MrSpock78** [comment] 2017-07-11 12:47
This sounds so easy, but as I told you I´m not a Developer. I really tried to follow your steps but this didn´t work for me.
Can you upload this as kind of Map-Fix-Plugin or will this be fixed in ProtocolSupport?

**Comment by MrPowerGamerBR** [comment] 2017-07-11 12:49
@MrSpock78 well, you could wait Shevchik's fix, since he already said that this is a ProtocolSupport issue.

**Comment by Shevchik** [comment] 2017-07-12 15:26
Should be fixed now

**Comment by MrSpock78** [comment] 2017-07-12 18:56
@Shevchik thanks a lot for trying to fix this.
You can join my testserver if you want to see what issue I still have: 31.172.80.145   
I don´t know if this is related to the plugins or ProtocolSupport.

**Comment by Shevchik** [comment] 2017-07-13 20:15
Looks like a map item damage id missmatch,

**Comment by Brokkonaut** [comment] 2017-07-13 20:43
I can confirm this bug

**Comment by MrSpock78** [comment] 2017-07-13 20:43
On 1.12 everything is fine with all maps. 
Seems like it randomly inserts  other maps or cached mapd from the one plugin where it works on every version.
I don´t know why, but only one plugin creates maps which are visible to all versions.
![map5225](https://user-images.githubusercontent.com/28217121/28186639-3fc6dd72-681c-11e7-8c67-a0ea0dbb3e22.png)
![map5226](https://user-images.githubusercontent.com/28217121/28186643-424cee56-681c-11e7-84f8-ffcc163d0d96.png)
![map5227](https://user-images.githubusercontent.com/28217121/28186644-444cf732-681c-11e7-8a13-b9ddec6ee8ff.png)
![map5228](https://user-images.githubusercontent.com/28217121/28186645-4645620e-681c-11e7-93e2-c46787cc1482.png)

[maps.zip](https://github.com/ProtocolSupport/ProtocolSupport/files/1146604/maps.zip)

**Comment by Shevchik** [comment] 2017-07-13 20:44
Try latest dev build. Most likely in previous builds the maps with data > Short.MAX_VALUE were clamped

**Comment by Shevchik** [comment] 2017-07-13 20:47
Also i meant the whole map with item frames and such, not just map contents.

**Comment by MrSpock78** [comment] 2017-07-13 21:00
Thanks for helping me with this issue.
I´m now on latest dev build now. 
How can i send you the whole map with item frames? Feel free to join my testserver if it helps?
31.172.80.145
Tell me what I can do to help you with this.

**Comment by Shevchik** [comment] 2017-07-13 21:30
The issues is that while i created the remap table for colors, i din't use it... Will fix it soon.

**Comment by Shevchik** [comment] 2017-07-13 21:43
Should work better now

**Comment by MrSpock78** [comment] 2017-07-13 21:51
Can I contact you on Steam or something? Please add me: MrSpock78

**Comment by gdude2002** [comment] 2017-07-13 21:56
You can always chat on the [Discord server](https://discord.gg/x935y8p)

**Closed** 2017-07-13 23:02 UTC
Labels: bug
