### ISSUE TITLE
1.11.2 cant write in blank books

### ISSUE THREAD

**Issue by alekso56** [ProtocolSupport/ProtocolSupport#367] opened 2017-01-25 21:14 UTC
Unable to write in blank books.

**Comment by Shevchik** [comment] 2017-01-26 08:25
Does it affect any other version?

**Comment by MrPowerGamerBR** [comment] 2017-01-27 13:04
What would be "blank books"? Book and quill? If that's what it is, I could write on a book and quill book in 1.11.2 without any issues.

Also no issues in 1.8.8. (Except #363 but that isn't related to this issue)

Here's what I tried:
1. Opened a book and quill, no issues.
2. Wrote something and closed the book, no issues.
3. Wrote something in other pages and closed the book, no issues.
4. Signed the book, no issues after opening it.

**Comment by alekso56** [comment] 2017-01-27 14:39
Yes, book and quill. Using a forge client. Ill test more when i come home.

**Comment by MrPowerGamerBR** [comment] 2017-01-27 14:46
@alekso56 maybe it is a incompatibility with Forge... or maybe your ProtocolSupport version is outdated.

Unless if it is doing a specific way that causes that bug.

**Comment by alekso56** [comment] 2017-01-27 16:39
Any build above 655 breaks book writing.
Tested using paperspigot and spigot fully vanilla 1.11.2 clients on 1.11.2 server
no other plugins installed.

**Comment by MrPowerGamerBR** [comment] 2017-01-27 16:59
@alekso56 oh, okay.

Yeah, now I can confirm the issue, I was running a outdated ProtocolSupport version (which doesn't have this issue) so it is a recent change that caused this.

Reproducing is easy... get a book and you will see that you can't write to it.

However, if you get a book, go next one page and go back, you will be able to write on it.

**Comment by govnojon** [comment] 2017-02-10 08:03
Soon correct? It happened after a commit ...
![image](https://cloud.githubusercontent.com/assets/18377011/22818864/1066c474-ef78-11e6-86cb-ebc3e308fad1.png)
@Shevchik , correct yourself.

**Comment by Shevchik** [comment] 2017-02-11 05:16
It's actually a mojang issue that i accidentally triggered. (This one: https://bugs.mojang.com/browse/MC-1685). It's triggered due to i actually now always create an empty nbt tag even if the item didn't have one. Will add a book transformer that always appends an empty page.

**Comment by Shevchik** [comment] 2017-02-11 05:37
Should be fixed now

**Comment by MrPowerGamerBR** [comment] 2017-02-11 11:25
@Shevchik can confirm, fixed in the latest development build.

However I also needed to update my Paper version because, for some reason, I couldn't write things to books until I updated Paper + ProtocolSupport.

```This server is running Paper version git-Paper-1056 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)```

**Closed** 2017-02-11 17:26 UTC
Labels: didnt check yet
