### ISSUE TITLE
The NBT of CanDestroy and CanPlaceOn error

### ISSUE THREAD

**Issue by TNG-China** [ProtocolSupport/ProtocolSupport#1193] opened 2019-12-22 15:59 UTC
Server ver: 1.13
client ver: 1.12

When I get an item has candestroy nbt with oak_log(1.13 material name), But it's can break log in 1.12 and show missingno:
![image](https://user-images.githubusercontent.com/21065884/71324210-0402f680-2517-11ea-8756-47c75e623726.png)

But in 1.13 is right:
![image](https://user-images.githubusercontent.com/21065884/71324212-06fde700-2517-11ea-9811-0fd7f73c18ee.png)

Even I add two name: candestroy: log, oak_log, not working.

**Comment by Shevchik** [comment] 2019-12-22 18:43
Duplicate of #1105

**Closed by Shevchik** 2019-12-22 18:43 UTC
