### ISSUE TITLE
 Must be within ~3 blocks to see entities

### ISSUE THREAD

**Issue by MWLVegas** [ProtocolSupport/ProtocolSupport#995] opened 2018-12-19 14:13 UTC
PS build #326, Spigot 1.13.2 (667bdd6, most recent as of this morning)

As stated above, you have to be within approx 3 blocks to see any entities, both living and non-living. Problem happens with client vers 1.13.2, 1.12 and 1.11 - did not check any others.

**Comment by RaidAndFade** [comment] 2018-12-19 15:12
Can reproduce on 1.13.2 client.

**Comment by Alchemi1963** [comment] 2018-12-19 15:54
Can confirm 1.13.2. I run the latest ps and spigot.

**Comment by Speentie8081** [comment] 2018-12-19 16:03
More like 10 blocks roughly, but yeah I'm also able to reproduce the issue on 1.13.2
[https://i.imgur.com/tj0R7Nf.png](https://i.imgur.com/tj0R7Nf.png)
[https://i.imgur.com/WlkjiyF.png](https://i.imgur.com/WlkjiyF.png)

**Comment by MithrandirCraft** [comment] 2018-12-19 20:12
Hey, same here, looks like when you go over the 11'th block (12th), entities dissappear, and once you go back to the 7th proximity block they come back.

**Comment by SmallSansSerif** [comment] 2018-12-20 01:14
Yes can confirm this as well.

**Comment by Mgazul** [comment] 2018-12-20 11:30
Yes can confirm this as well.

**Comment by BBoyJD10** [comment] 2018-12-20 14:20
Can confirm

**Comment by Shevchik** [comment] 2018-12-20 15:21
Should be fixed now

**Closed** 2018-12-21 13:46 UTC
